name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🔎 Analyzer'
    labels:
      - 'natlint🐑'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug🪲'
  - title: '🧰 Maintenance'
    collapse-after: 3
    labels:
      - 'infrastructure🚊'
      - 'chore'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  default: minor
template: |
  ## What's Changed

  $CHANGES
