plugins {
    id 'java-library'
    id 'jvm-test-suite'
    id 'org.sonarqube' version '6.3.1.5724'
    id 'com.diffplug.spotless' version '6.2.0'
    id 'signing'
    id 'com.vanniktech.maven.publish' version '0.34.0'
    id "com.github.ben-manes.versions" version "0.52.0"
}

spotless {
	format 'gradle', {
		target '.gradle'
		indentWithTabs()
	}
	java {
		target '**/src/*/java/**/*.java'
		toggleOffOn('"""', '"""')
		indentWithTabs()
		eclipse().configFile('EclipseFormatter.xml')
	}
}

allprojects {
	apply plugin: 'java-library'
	apply plugin: 'jacoco'

	group = 'org.amshove.natural'

	java {
		toolchain {
			languageVersion = JavaLanguageVersion.of(javaVersion)
		}
	}

    compileJava.options.encoding = 'UTF-8'
    compileTestJava.options.encoding = 'UTF-8'

	tasks.withType(JavaCompile).configureEach {
		options.release.set(Integer.valueOf(project.property('javaVersion')))
	}

	repositories {
		mavenCentral()
	}

	javadoc.options.addStringOption('Xdoclint:none', '-quiet')
}


subprojects {
	dependencies {
		implementation libs.guava

		testImplementation libs.testing.assertj
		testImplementation(platform(libs.testing.junit.jupiter))
		testImplementation('org.junit.jupiter:junit-jupiter')
	}

    testing {
        suites {
            test {
                useJUnitJupiter()
            }

            configureEach {
                targets {
                    all {
                        testTask.configure {
                            testLogging {
                                events "skipped", "failed"
                                showStandardStreams = true
                                exceptionFormat = 'full'
                            }
                        }
                    }
                }
            }
        }
    }

	jacocoTestReport {
		reports {
			html.required = true
			xml.required = true
			csv.required = false
		}
	}
}

task cover(type: JacocoReport) {
	dependsOn = subprojects.test
	dependsOn += test

	additionalSourceDirs.setFrom files(subprojects.sourceSets.main.allSource.srcDirs)
	sourceDirectories.setFrom files(subprojects.sourceSets.main.allSource.srcDirs)
	classDirectories.setFrom files(subprojects.sourceSets.main.output)
	executionData.setFrom project.fileTree(dir: '.', include: '**/build/jacoco/test.exec')

	reports {
		html.required = true
		xml.required = true
		csv.required = false
	}
}

task testReport(type: TestReport) {
	destinationDirectory = file("$buildDir/reports/allTests")
	testResults.from(subprojects.collect { it.tasks.withType(Test) })
}

sonarqube {
	properties {
		property "sonar.projectKey", "MarkusAmshove_natls"
		property "sonar.organization", "markusamshove"
		property "sonar.host.url", "https://sonarcloud.io"
		property 'sonar.coverage.jacoco.xmlReportPaths', "${rootProject.buildDir}/reports/jacoco/cover/cover.xml"
		property 'sonar.coverage.exclusions', 'tools/**/*,libs/natlint/src/main/java/org/amshove/natlint/cli/sinks/*.*'
	}
}

project.tasks.getByPath('natlint:test').dependsOn(project.tasks.getByPath('natparse:test'))
project.tasks['sonar'].dependsOn cover
project.tasks['cover'].dependsOn spotlessJava
project.tasks['cover'].dependsOn spotlessGradle

def isNonStable = { String version ->
  def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { it -> version.toUpperCase().contains(it) }
  def regex = /^[0-9,.v-]+(-r)?$/
  return !stableKeyword && !(version ==~ regex)
}

tasks.named("dependencyUpdates").configure {
  rejectVersionIf {
    isNonStable(it.candidate.version) && !isNonStable(it.currentVersion)
  }
}
