package org.amshove.natgen.commands;

import io.swagger.parser.OpenAPIParser;
import io.swagger.v3.parser.core.models.ParseOptions;
import org.amshove.natgen.CliOutput;
import org.amshove.natgen.NatGen;
import org.amshove.natgen.generators.ModuleGenerator;
import org.amshove.natgen.generators.RequestDocumentForOpenApiGenerator;
import org.amshove.natparse.natural.project.NaturalFileType;
import picocli.CommandLine;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.Callable;

@CommandLine.Command(name = "request-document")
public class RequestDocumentCommand implements Callable<Integer>
{
	private static final CliOutput output = new CliOutput();

	@CommandLine.Parameters(arity = "1")
	File openApiSchemaFile;

	@Override
	public Integer call() throws Exception
	{
		var options = new ParseOptions();
		options.setFlatten(true);
		var openApiParseResult = new OpenAPIParser().readLocation(openApiSchemaFile.getAbsolutePath(), null, options);
		var openApi = openApiParseResult.getOpenAPI();

		if (!openApiParseResult.getMessages().isEmpty())
		{
			output.error("Error(s) during Open API parsing");
			for (var message : openApiParseResult.getMessages())
			{
				output.error("Open API: %s", message);
			}
			return 1;
		}

		// TODO: Parameter
		var moduleBaseName = "WETVOR";
		var moduleNumberCharacterAmount = 8 - moduleBaseName.length();
		var moduleNameFormat = moduleBaseName + "%0" + moduleNumberCharacterAmount + "d";
		var currentModuleNumber = 1;

		for (var path : openApi.getPaths().entrySet())
		{
			for (var httpMethodOperation : path.getValue().readOperationsMap().entrySet())
			{
				var theMethod = httpMethodOperation.getKey().toString();
				var theOperation = httpMethodOperation.getValue();

				var context = new RequestDocumentForOpenApiGenerator(openApi)
					.generate(theMethod, path.getKey(), theOperation);

				// TODO: Validate possible number of modules according to paths/operations
				var moduleName = String.format(moduleNameFormat, currentModuleNumber++);

				var moduleGenerator = new ModuleGenerator();

				moduleGenerator.addDocumentationLine("%s %s".formatted(theMethod, path.getKey()));
				addGeneratorComment(moduleGenerator);

				var generatedModule = moduleGenerator.generate(context, NaturalFileType.SUBPROGRAM);
				var modulePath = Path.of(moduleName + ".NSN");

				output.info("%s %s => %s", theMethod, path.getKey(), modulePath);

				Files.writeString(modulePath, generatedModule, StandardCharsets.UTF_8);
			}
		}

		return 0;
	}

	private void addGeneratorComment(ModuleGenerator moduleGenerator)
	{

		moduleGenerator.addDocumentationLine("");
		moduleGenerator.addDocumentationLine("Generated by NatGen version %s".formatted(NatGen.VERSION));
	}
}
