FROM eclipse-temurin:25

RUN mkdir /work && chown 1000:1000 /work

USER 1000
ADD --chown=1000:1000 ./libs/natlint/build/libs/natlint.jar /opt/natlint.jar

WORKDIR /work

ENTRYPOINT [ "java", "-jar", "/opt/natlint.jar" ]
