package org.amshove.natgen;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.assertj.core.api.AssertionsForInterfaceTypes.assertThat;

class RequestDocumentCommandShould extends NatGenTest
{
	private Path yamlPath;

	@Test
	void generateAPdaAndSubprogramPairForASingleGet() throws IOException
	{
		writeSpec("""
			openapi: 3.1.0
			components:
			  schemas:
			    UUID:
			      type: string
			      format: uuid
			      pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
			    Forecast:
			      type: object
			      properties:
			        id:
			          $ref: "#/components/schemas/UUID"
			        temperature:
			          type: number
			          format: double
			        description:
			          type: string
			paths:
			  /weather:
			    get:
			      summary: This is a summary
			      description: |
			        This is a long description that will hopefully
			        be part of the module documentation.
			      responses:
			        "200":
			          description: OK
			          content:
			            application/json:
			              schema:
			                type: array
			                items:
			                  $ref: "#/components/schemas/Forecast"
			      tags:
			      - Weatherforecast
			      - GET request
			info:
			
			""");

		assertRunsSuccessful("request-document", yamlPath.toString(), "--base-name", "FORE", "--output-dir", workingDirectory.toString());

		var subprogramPath = workingDirectory.resolve("FORE001N.NSN");
		var subprogramSource = Files.readString(subprogramPath);
		var pdaPath = workingDirectory.resolve("FORE001O.NSA");
		var pdaSource = Files.readString(pdaPath);

		assertThat(pdaSource).isEqualToNormalizingNewlines("""
			/***********************************************************************
			/** GET /weather
			/** Summary: This is a summary
			/** This is a long description that will hopefully
			/** be part of the module documentation.
			/**
			/** Tags:
			/** - Weatherforecast
			/** - GET request
			/**
			/** Generated by NatGen version null
			/***********************************************************************
			DEFINE DATA PARAMETER
			/* >Natural Source Header 000000
			/* :Mode S
			/* :CP
			/* <Natural Source Header
			1 FORE001O
			  2 #RESPONSE-200
			    3 #INLINERESPONSE (1:*)
			      4 #ID (A36)
			      4 #TEMPERATURE (N12,7)
			      4 #DESCRIPTION (A) DYNAMIC
			END-DEFINE
			""");

		assertThat(subprogramSource).isEqualToNormalizingNewlines("""
			/* >Natural Source Header 000000
			/* :Mode S
			/* :CP
			/* <Natural Source Header
			/***********************************************************************
			/** GET /weather
			/** Summary: This is a summary
			/** This is a long description that will hopefully
			/** be part of the module documentation.
			/**
			/** Tags:
			/** - Weatherforecast
			/** - GET request
			/**
			/** Generated by NatGen version null
			/***********************************************************************
			DEFINE DATA
			PARAMETER
			1 #P-BASE-URL (A) DYNAMIC BY VALUE
			PARAMETER USING FORE001O
			LOCAL
			1 ##REQUEST
			  2 #URL (A) DYNAMIC
			1 ##RESPONSE
			  2 #CODE (I4)
			  2 #BODY (A) DYNAMIC
			1 ##PARSE-200
			  2 #PATH (A) DYNAMIC
			  2 #VALUE (A) DYNAMIC
			  2 #ERR-CODE (I4)
			  2 #ERR-SUBCODE (I4)
			  2 #S-#INLINERESPONSE (I4)
			1 #JSON-SOURCE (A) DYNAMIC
			END-DEFINE

			COMPRESS #P-BASE-URL '/weather' INTO ##REQUEST.#URL LEAVING NO SPACE

			REQUEST DOCUMENT FROM ##REQUEST.#URL
			  WITH
			    HEADER NAME 'REQUEST-METHOD' VALUE 'GET'
			  RETURN
			    PAGE ##RESPONSE.#BODY
			    RESPONSE ##RESPONSE.#CODE

			DECIDE ON FIRST VALUE OF ##RESPONSE.#CODE
			  VALUE 200
			    PERFORM HANDLE-200
			  NONE VALUE
			    IGNORE
			END-DECIDE


			/***********************************************************************
			DEFINE SUBROUTINE HANDLE-200
			/***********************************************************************

			#JSON-SOURCE := #BODY
			PARSE JSON #JSON-SOURCE INTO PATH ##PARSE-200.#PATH VALUE ##PARSE-200.#VALUE GIVING ##PARSE-200.#ERR-CODE SUBCODE ##PARSE-200.#ERR-SUBCODE
			  DECIDE ON FIRST VALUE OF ##PARSE-200.#PATH
			    VALUE '/(/<'
			      ADD 1 TO ##PARSE-200.#S-#INLINERESPONSE
			      EXPAND ARRAY FORE001O.#INLINERESPONSE TO (1:##PARSE-200.#S-#INLINERESPONSE)
			    VALUE '/(/</id/$'
			      FORE001O.#ID(#S-#INLINERESPONSE) := ##PARSE-200.#VALUE
			    VALUE '/(/</temperature/$'
			      FORE001O.#TEMPERATURE(#S-#INLINERESPONSE) := VAL(##PARSE-200.#VALUE)
			    VALUE '/(/</description/$'
			      FORE001O.#DESCRIPTION(#S-#INLINERESPONSE) := ##PARSE-200.#VALUE
			    NONE VALUE
			      IGNORE
			  END-DECIDE
			END-PARSE

			END-SUBROUTINE

			END
			""");
	}

	private void writeSpec(String spec) throws IOException
	{
		yamlPath = workingDirectory.resolve("opanapi.yaml");
		Files.writeString(yamlPath, spec, StandardCharsets.UTF_8);
	}
}
