package org.amshove.natgen;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.assertj.core.api.AssertionsForInterfaceTypes.assertThat;

class RequestDocumentCommandShould extends NatGenTest
{
	private Path yamlPath;

	@Test
	void generateAPdaAndSubprogramPairForASingleGet() throws IOException
	{
		writeSpec("""
			openapi: 3.1.0
			components:
			  schemas:
			    UUID:
			      type: string
			      format: uuid
			      pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
			    Forecast:
			      type: object
			      properties:
			        id:
			          $ref: "#/components/schemas/UUID"
			        temperature:
			          type: number
			          format: double
			        description:
			          type: string
			paths:
			  /weather:
			    get:
			      responses:
			        "200":
			          description: OK
			          content:
			            application/json:
			              schema:
			                type: array
			                items:
			                  $ref: "#/components/schemas/Forecast"
			      summary: Index
			      tags:
			      - Weatherforecast
			info:
			
			""");

		assertRunsSuccessful("request-document", yamlPath.toString(), "--base-name", "FORE", "--output-dir", workingDirectory.toString());

		var subprogramPath = workingDirectory.resolve("FORE001N.NSN");
		var subprogramSource = Files.readString(subprogramPath);
		var pdaPath = workingDirectory.resolve("FORE001P.NSA");
		var pdaSource = Files.readString(pdaPath);

		assertThat(pdaSource).isEqualToNormalizingNewlines("""
			/***********************************************************************
			/** GET /weather
			/**
			/** Generated by NatGen version null
			/***********************************************************************
			DEFINE DATA PARAMETER
			/* >Natural Source Header 000000
			/* :Mode S
			/* :CP
			/* <Natural Source Header
			1 FORE001P
			  2 #RESPONSE-200
			    3 #INLINERESPONSE (1:*)
			      4 #ID (A36)
			      4 #TEMPERATURE (F8)
			      4 #DESCRIPTION (A) DYNAMIC
			END-DEFINE
			""");

		assertThat(subprogramSource).isEqualToNormalizingNewlines("""
			/* >Natural Source Header 000000
			/* :Mode S
			/* :CP
			/* <Natural Source Header
			/***********************************************************************
			/** GET /weather
			/**
			/** Generated by NatGen version null
			/***********************************************************************
			DEFINE DATA
			PARAMETER
			1 #P-BASE-URL (A) DYNAMIC
			PARAMETER USING FORE001P
			LOCAL
			1 ##REQUEST
			  2 #URL (A) DYNAMIC
			1 ##RESPONSE
			  2 #CODE (I4)
			  2 #BODY (A) DYNAMIC
			1 ##JSON-PARSING
			  2 #PATH (A) DYNAMIC
			  2 #VALUE (A) DYNAMIC
			  2 #ERR-CODE (I4)
			  2 #ERR-SUBCODE (I4)
			  2 #S-#INLINERESPONSE (I4)
			1 #JSON-SOURCE (A) DYNAMIC
			END-DEFINE

			COMPRESS #P-BASE-URL '/weather' INTO ##REQUEST.#URL LEAVING NO SPACE

			REQUEST DOCUMENT FROM ##REQUEST.#URL
			  WITH
			    HEADER NAME 'REQUEST-METHOD' VALUE 'GET'
			  RETURN
			    PAGE ##RESPONSE.#BODY
			    RESPONSE ##RESPONSE.#CODE

			DECIDE ON FIRST VALUE OF ##RESPONSE.#CODE
			  VALUE 200
			    PERFORM HANDLE-200
			  NONE VALUE
			    IGNORE
			END-DECIDE


			/***********************************************************************
			DEFINE SUBROUTINE HANDLE-200
			/***********************************************************************

			#JSON-SOURCE := #BODY
			PARSE JSON #JSON-SOURCE INTO PATH ##JSON-PARSING.#PATH VALUE ##JSON-PARSING.#VALUE GIVING ##JSON-PARSING.#ERR-CODE SUBCODE ##JSON-PARSING.#ERR-SUBCODE
			  DECIDE ON FIRST VALUE OF ##JSON-PARSING.#PATH
			    VALUE '(/<'
			      ADD 1 TO ##JSON-PARSING.#S-#INLINERESPONSE
			      EXPAND ARRAY FORE001P.#INLINERESPONSE TO (1:##JSON-PARSING.#S-#INLINERESPONSE)
			    VALUE '(/</id/$'
			      FORE001P.#ID(#S-#INLINERESPONSE) := ##JSON-PARSING.#VALUE
			    VALUE '(/</temperature/$'
			      FORE001P.#TEMPERATURE(#S-#INLINERESPONSE) := VAL(##JSON-PARSING.#VALUE)
			    VALUE '(/</description/$'
			      FORE001P.#DESCRIPTION(#S-#INLINERESPONSE) := ##JSON-PARSING.#VALUE
			    NONE VALUE
			      IGNORE
			  END-DECIDE
			END-PARSE

			END-SUBROUTINE

			END
			""");
	}

	private void writeSpec(String spec) throws IOException
	{
		yamlPath = workingDirectory.resolve("opanapi.yaml");
		Files.writeString(yamlPath, spec, StandardCharsets.UTF_8);
	}
}
