name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
  merge_group:

jobs:
  formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check Formatting
        run: ./gradlew spotlessCheck

  javadoc:
    name: Validate Javadoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check Formatting
        run: ./gradlew javadoc

  test-maven-release:
    name: Test Maven publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish to Maven local
        env:
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_SECRET }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSPHRASE }}
        run: ./gradlew publishToMavenLocal --no-daemon

  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
      fail-fast: false
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'gradle'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew check cover fatJar -x spotlessCheck --no-daemon

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit-test-results-${{ matrix.os }}
          path: '**/build/test-results/test/TEST-*.xml'
          retention-days: 1

      - name: Save PR number
        if: github.event_name == 'pull_request' && matrix.os == 'ubuntu-latest'
        run: echo ${{ github.event.number }} > PR_NUMBER.txt

      - name: Archive PR number
        if: github.event_name == 'pull_request' && matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: PR_NUMBER
          path: PR_NUMBER.txt

      - name: Stop daemon for caching
        run: ./gradlew --stop
