name: Release Jars
on:
  push:
    branches:
      - release-test

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
 
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew publish -Pversion=0.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}