name: Sonar

on:
 push:
   branches:
     - main
 pull_request:
   types: [opened, synchronize, reopened]

jobs:
  Sonar:
    runs-on: ubuntu-latest
    env:
      HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'temurin'
          cache: 'gradle'

      - name: Compile
        run: ./gradlew compileJava compileTestJava

      - name: SonarCloud Scan on PR
        if: github.event_name == 'pull_request'
        run: ./gradlew check sonar -Dsonar.scm.revision=${{ github.event.workflow_run.head_sha }} -Dsonar.pullrequest.key=${{ github.event.number }} -Dsonar.pullrequest.branch=${{ github.event.head.sha }} -Dsonar.pullrequest.base=${{ github.event.base.ref }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: SonarCloud Scan on push
        if: github.event_name == 'push' && github.repository == 'MarkusAmshove/natls'
        run: ./gradlew check sonar -Dsonar.scm.revision=${{ github.sha }} -Dsonar.branch.name=$HEAD_BRANCH
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
